apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  #name: letsencrypt-staging
  name: letsencrypt-prod
spec:
  acme:
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rodrigopetrellas@gmail.com
    privateKeySecretRef:
      #name: letsencrypt-staging
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux